otel:
  resource:
    attributes:
      service:
        name: ${spring.application.name}

  instrumentation:
    common:
      db-statement-sanitizer:
        enabled: false
    jdbc:
      enabled: true
      statement-sanitizer:
        enabled: false

  traces:
    exporter: none
  metrics:
    exporter: none
  logs:
    exporter: none



spring:
  application:
    name: ifast-itp-assignment

  datasource:
    #  Using p6spy
    #    url: jdbc:p6spy:h2:mem:testdb;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE
    #    driver-class-name: com.p6spy.engine.spy.P6SpyDriver

    #  Using normal database
    url: jdbc:h2:mem:testdb;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE
    driver-class-name: org.h2.Driver

    #    #  Using OpenTelementry
    #    url: jdbc:otel:h2:mem:testdb;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE
    #    driver-class-name: io.opentelemetry.instrumentation.jdbc.OpenTelemetryDriver
    username: root
    password: root

  sql:
    init:
      mode: always


  h2:
    console:
      enabled: true
      path: /h2-console

  cache:
    type: caffeine

  devtools:
    restart:
      enabled: true
    livereload:
      enabled: true

  jpa:
    database: h2
    hibernate:
      ddl-auto: update
    # Disable default Hibernate SQL logging
    show-sql: false
    database-platform: org.hibernate.dialect.H2Dialect
    properties:
      hibernate:
        format_sql: true


management:
  endpoint:
    health:
      show-details: always
  health:
    db:
      enabled: true
    diskspace:
      enabled: true
  tracing:
    propagation:
      type: w3c
    enabled: true
    sampling:
      probability: 1.0
  observations:
    annotations:
      enabled: true
    http:
      server:
        requests:
          write-trace-header: true

server:
  port: 8080
  servlet:
    context-path: /api/v1/

springdoc:
  swagger-ui:
    url: ../v3/api-docs

logging:
  level:
#    root: INFO
#    io.opentelemetry.instrumentation.jdbc: DEBUG
#    io.opentelemetry.javaagent.instrumentation.jdbc: DEBUG
#    sql: DEBUG
#    org.springframework.jdbc.core: DEBUG
#    p6spy: INFO
#    com.p6spy.engine.spy.P6SpyDriver: DEBUG

otel:
  service:
    name: ifast-itp-assignment
  traces:
    #    exporter: none
    #  propagators:
    #    - tracecontext
    hikaricp:
      enabled: true
  #
  #  # ======= exporters =======
  #  traces:
  #    exporter: logging
  #  metrics:
  #    exporter: logging
  #  logs:
  #    exporter: logging

  instrumentation:
    common:
      db-statement-sanitizer:
        enabled: false
      default-enabled: false
    jdbc:
      enabled: true
      statement-sanitizer:
        enabled: false
    logback-appender:
      enabled: false
    logback-mdc:
      enabled: true
