#!/bin/sh
# gradle-githook

$(echo "C:\Users\fyier\Desktop\projects\my-growth\@Archived\3_实践笔记\2025-ifast\checkstyle-cicd\config\gradlew") someTask
[ $? -gt 0 ] && exit 1

someShell
[ $? -gt 0 ] && exit 1

exit 0